apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansparservice
  namespace: family
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  ansparservice
  template:
    metadata:
      labels:
        app:  ansparservice
    spec:
      containers:
      - name:  ansparservice
        image: luke19/familyansparservice:<VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m
          requests:
            memory: 256Mi
            cpu: 150m
        env:
        - name: DB_ANSPAREN_HOST
          valueFrom:
            configMapKeyRef:
              name: family-config
              key: DB_HOST
        - name: DB_ANSPAREN_DB
          valueFrom:
            secretKeyRef:
              name: family-secret
              key: ANSPAR_DB
        - name: DB_ANSPAREN_USER
          valueFrom:
            secretKeyRef:
              name: family-secret
              key: ANSPAR_USER
        - name: DB_ANSPAREN_PASS
          valueFrom:
            secretKeyRef:
              name: family-secret
              key: ANSPAR_PASS
        ports:
        - containerPort: 8080 #Expose containerport to the pod
        livenessProbe: #Check that pod is ready
          httpGet:
            path: / #path to check
            port: 8080
          initialDelaySeconds: 10 #start checking after 30 seconds
          periodSeconds: 10 #check every 30 seconds
          failureThreshold: 10
        readinessProbe: #Check that pod is healthy
          httpGet:
            path: / #path to check
            port: 8080 #port to check
          initialDelaySeconds: 15 #start checking after 15 seconds
          periodSeconds: 10 #check every 3 seconds
          failureThreshold: 10