apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ansparservice
  namespace: family
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ansparservice
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60