apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ansparservice
  namespace: family
  labels:
    app: ansparservice
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: ansparservice