apiVersion: v1
kind: Service
metadata:
  name: ansparservice
  namespace: family
  labels:
    app: ansparservice
spec:
  type: ClusterIP
  ports:
   - port: 8080
     name: ansparservice
  selector:
   app: ansparservice